# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class SendNotificationPostRequest(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    SendNotificationPostRequest - a model defined in OpenAPI

        api_key: The api_key of this SendNotificationPostRequest.
        message: The message of this SendNotificationPostRequest.
    """

    api_key: str = Field(alias="apiKey")
    message: str = Field(alias="message")

SendNotificationPostRequest.update_forward_refs()
